services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server
    networks:
      - url-shortener
  app:
    build: .
    ports:
      - "3000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: "${REDIS_HOST:-redis}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-}"
    networks:
      - url-shortener

volumes:
    data:

networks:
  url-shortener:
    driver: bridge
